// Generated by CoffeeScript 2.7.0
var is_object_literal, normalize;

is_object_literal = function(obj) {
  var test;
  test = obj;
  if (typeof obj !== 'object' || obj === null) {
    return false;
  } else {
    if (Object.getPrototypeOf(test) === null) {
      return true;
    }
    while (!false) {
      if (Object.getPrototypeOf(test = Object.getPrototypeOf(test)) === null) {
        break;
      }
    }
    return Object.getPrototypeOf(obj) === test;
  }
};

normalize = function(...args) {
  var arg, i, items, j, len, options;
  items = [];
  options = {
    concurrency: 1,
    pause: false,
    relax: false
  };
  for (i = j = 0, len = args.length; j < len; i = ++j) {
    arg = args[i];
    if (Array.isArray(arg)) {
      items = [...items, ...arg];
    } else if (is_object_literal(arg)) {
      options = {...options, ...arg};
    } else if (typeof arg === 'function') {
      options = {
        ...options,
        handler: arg
      };
    } else if (typeof arg === 'boolean') {
      options = {
        ...options,
        concurrency: typeof arg ? -1 : 1
      };
    } else if (typeof arg === 'number') {
      options = {
        ...options,
        concurrency: arg
      };
    } else {
      throw Error(`Invalid argument: argument at position ${i} must be one of array, object, function, boolean or number, got ${JSON.stringify(argument)}`);
    }
  }
  return {
    items: items,
    options: options
  };
};

export default function(...args) {
  var all, internal, items, options, scheduler, stack, state;
  ({items, options} = normalize.apply(null, arguments));
  stack = [];
  state = {
    error: false,
    paused: options.pause,
    running: 0,
    count: -1
  };
  internal = {
    pump: function() {
      var item;
      if (!stack.length) {
        return;
      }
      if (state.error && !options.relax) {
        while (item = stack.shift()) {
          item.reject.call(null, state.error);
        }
        return;
      }
      if (state.paused) {
        return;
      }
      if (options.concurrency > 0 && state.running === options.concurrency) {
        return;
      }
      state.running++;
      item = stack.shift();
      return setImmediate(async function() {
        var error, result;
        try {
          state.count++;
          result = options.handler ? (await options.handler.call(null, item.handler, state.count)) : typeof item.handler === 'function' ? (await item.handler.call()) : (await item.handler);
          state.running--;
          item.resolve.call(null, result);
          return internal.pump();
        } catch (error1) {
          error = error1;
          state.running--;
          state.error = error;
          item.reject.call(null, error);
          return internal.pump();
        }
      });
    }
  };
  all = function(items, options) {
    return new Promise(function(resolve, reject) {
      var isArray, item;
      isArray = Array.isArray(items);
      if (isArray) {
        return Promise.all((function() {
          var j, len, results;
          results = [];
          for (j = 0, len = items.length; j < len; j++) {
            item = items[j];
            results.push(all(item, options));
          }
          return results;
        })()).then(resolve, reject);
      } else {
        stack.push({
          handler: items,
          resolve: resolve,
          reject: reject,
          options: options
        });
        return internal.pump();
      }
    });
  };
  scheduler = all(items);
  scheduler.get = function() {
    if (arguments.length === 0) {
      return {...options};
    }
    if (arguments.length === 1) {
      return options[arguments[0]];
    } else {
      throw Error(`Invalid argument: \`get\` expect one or two arguments, got ${arguments.length}`);
    }
  };
  scheduler.pause = function() {
    state.paused = true;
    return scheduler;
  };
  scheduler.call = function(items) {
    return all(items);
  };
  scheduler.resume = function() {
    state.paused = false;
    internal.pump();
    return scheduler;
  };
  return scheduler;
};
